### ISSUE TITLE
Question - Reload Command

### ISSUE THREAD

**Issue by Berenvonbaggins** [PYRRH4/CustomCommands#13]
Was wondering what the command to reload the plugin was? It has one I think because you do mention a "plugin reload system" on the Spigot page. Not a bug or an issue, just a question. Thanks :)! 

Spigot :  Version Unknown (latest as of Oct. 1st, 2018)

PyrCore :  Version 4.0.1

CustomCommands :  Version 2.4.1

**Comment by PYRRH4** [comment]
it's /pyr reload CustomCommands ^^
