### ISSUE TITLE
Custom command

### ISSUE THREAD

**Issue by Sjilli** [PYRRH4/CustomCommands#4]
### Issue description
my question is how or what plugin do I need to change a command into a different command?
I currently have a command "/uc menu main" however I want players to be able to use a custom command such as "/cosmetics" instead.

Sorry if it doesnt make much sense :/

### Versions

Spigot : Yes, latest version 

PyrCore : Yes, latest version

CustomCommands : Yes, latest version

**Comment by PYRRH4** [comment]
We'll keep talking about this on spigot on the message you sent me.
