### ISSUE TITLE
Can't understand how to use config. Please send help

### ISSUE THREAD

**Issue by Nesseley** [PYRRH4/CustomCommands#6]
**Hey!**
I'm trying to transelate and easy-up some long commands from other plugins. But I don't really understand how, as you only show how to send messages to players in the config. 

What I want to do:
**/chest add playername** makes the player do **/cmodify playername**

Commands.yml: https://pastebin.com/36DqsdSX
Can you show me an example of how to do this? I've been trying for hours and I just don't get it.

### Versions
Spigot : 1.12.2
PyrCore : 3.2.2
CustomCommands : 2.3.2

Thanks
- Nesseley

**Comment by PYRRH4** [comment]
Here you are : 
https://pastebin.com/HC59LvMJ
